apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: quickship-payment
  namespace: default
spec:
  replicas: 2
  strategy:
    blueGreen: 
      # The service users currently access
      activeService: quickship-payment-svc
      # The service ONLY for us to test the new version
      previewService: quickship-payment-preview
      # Stop and wait for human approval before switching traffic
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: quickship-payment
  template:
    metadata:
      labels:
        app: quickship-payment
    spec:
      containers:
      - name: payment-api
        # We are still on v1 for now. We will change this later to trigger the rollout.
        image: 592109679631.dkr.ecr.us-east-1.amazonaws.com/quickship-payment:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
