apiVersion: v1
kind: Service
metadata:
  name: quickship-payment-preview
  namespace: default
spec:
  selector:
    app: quickship-payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
